version: '2'
services:
  web:
    build:
      context: ..
      dockerfile: Deploy/Dockerfile
    volumes:
      - ..:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres
